package main

/*
import (
	"fmt"
)

func division(dividendo, divisor int) {
	// Se utiliza "defer" y funciones anonimas
	// Muestra el error del panico, pero el programa no Aborta la ejecución, se cacha el error.
	// Continua con la ejecución de programa.
	defer func() {
		if contenidoPanico := recover(); contenidoPanico != nil {
			fmt.Printf("Recuperando del Panic = %v \n", contenidoPanico)
		}
	}()

	validarDivisor(divisor)
	fmt.Printf("Imprimiendo el resultado de la Division = %d \n", dividendo/divisor)
}

func validarDivisor(divisor int) {
	if divisor == 0 {
		panic("Error.....")
	}

}
func main() {
	// Se util iza para la finalizacion del programa.
	division(10, 2)
	division(40, 3)
	division(12, 0)
	division(20, 4) // Continua con la ejecución del programa

}
*/
